cam0:
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0, 0, 0, 0]
  distortion_model: equidistant
  intrinsics: [417.5968851353022, 417.5968851353022, 512, 375]
  resolution: [1024, 750]
  rostopic: /sync/blackfly/downres/image
